### ISSUE TITLE
`BootSpec.__init__()` error on first nixos-rebuild post deployment

### ISSUE THREAD

**Issue by mairs8** [nix-community/nixos-anywhere#317]
After deploying with nixos-anywhere, my first nixos-rebuild switch gives the below error. 

is this a known issue?

```
 sudo nixos-rebuild switch --flake /home/billy/.dotfiles/NixOS-01#system                                                                                                                                 ─╯
building the system configuration...
Traceback (most recent call last):
  File "/nix/store/xznxfas4x3syacx53gcjpiv0k07xfg85-systemd-boot", line 344, in <module>
    main()
  File "/nix/store/xznxfas4x3syacx53gcjpiv0k07xfg85-systemd-boot", line 332, in main
    install_bootloader(args)
  File "/nix/store/xznxfas4x3syacx53gcjpiv0k07xfg85-systemd-boot", line 288, in install_bootloader
    remove_old_entries(gens)
  File "/nix/store/xznxfas4x3syacx53gcjpiv0k07xfg85-systemd-boot", line 197, in remove_old_entries
    bootspec = get_bootspec(gen.profile, gen.generation)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xznxfas4x3syacx53gcjpiv0k07xfg85-systemd-boot", line 105, in get_bootspec
    return bootspec_from_json(bootspec_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xznxfas4x3syacx53gcjpiv0k07xfg85-systemd-boot", line 110, in bootspec_from_json
    return BootSpec(**bootspec_json['org.nixos.bootspec.v1'], specialisations=specialisations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BootSpec.__init__() missing 1 required positional argument: 'initrdSecrets'
warning: error(s) occurred while switching to the new configuration
```

**Comment by Mic92** [comment]
No but I strongly assume this has nothing to do with nixos-anywhere. Looks like the systemd-boot-builder is unhappy with the output that it receives from this tool: https://github.com/NixOS/nixpkgs/blob/19581e2ce8bc43f898ef724f8072ebf62bebb325/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L116

You might be able to fork nixpkgs and add print statements to get out the whole json output to troubleshoot this.
